# Thank you ChatGPT. For once you were useful. Please learn C++ better and then maybe you'll have a chance at actually stealing peoples' jobs.
name: Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Set up Git
      run: |
        git config --global user.name "J-D-K"
        git config --global user.email "jkhbdev@gmail.com"

    - name: Commit and push documentation to gh-pages branch
      run: |
        git checkout --orphan gh-pages
        git rm -rf .  # Clean up any existing files

        # Move generated docs to the root
        mv html/* .

        # Commit and push
        git add .
        git commit -m "Update Doxygen documentation"
        git push --force --set-upstream origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
